[project]
name = "spotify-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[all]>=0.116.2",
    "kagglehub>=0.3.13",
    "pandas>=2.3.2",
    "scikit-learn>=1.7.2",
    "streamlit>=1.49.1",
]
